config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get 'users/edit' => 'devise_invitable/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise_invitable/registrations#update', :as => 'user_registration'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  post '/invite', to: 'home#invite'

  resources :wichtelrundes, only: [:show] do
    resources :wichtels, only: [:create, :update, :destroy]

    member do
      get ':uuid', action: :sender_show, as: :sender
      patch ':uuid', action: :sender_update
      put ':uuid', action: :sender_update
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wichtels
  has_many :wichtelrundes, through: :wichtels
end

app/models/wichtel.rb
class Wichtel < ApplicationRecord
  belongs_to :user
  belongs_to :wichtelrunde
end

app/models/wichtelrunde.rb
class Wichtelrunde < ApplicationRecord
  has_many :wichtels
  has_many :users, through: :wichtels

  scope :should_draw_lots, -> {
    where("register_until < ? AND ship_until >= ?", DateTime.now, DateTime.now)
  }

  def registration_over
    self.register_until < DateTime.now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @current_wichtelrunden = Wichtelrunde.where("register_until >= ? OR ship_until >= ?", DateTime.now, DateTime.now).order(register_until: :desc)
    @past_wichtelrunden = Wichtelrunde.where("register_until < ? AND ship_until < ?", DateTime.now, DateTime.now).order(register_until: :asc)
  end

  def invite
    User.invite! invite_params

    flash[:notice] = t(".success")

    redirect_to root_path
  end

  private
    def invite_params
      params.permit(:email)
    end
end

app/controllers/wichtelrundes_controller.rb
class WichtelrundesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wichtelrunde, only: [:show, :sender_show, :sender_update]
  before_action :set_sender_wichtel, only: [:sender_show, :sender_update]

  def show
    @wichtel = current_user.wichtels.where(wichtelrunde: @wichtelrunde).first
    unless @wichtel
      @wichtel = Wichtel.new
    end
  end

  def sender_show
  end

  def sender_update
    @wichtel.update sender_wichtel_params

    flash[:notice] = t(".updated")

    redirect_to sender_wichtelrunde_path(@wichtelrunde, @wichtel.lot_uuid)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wichtelrunde
      @wichtelrunde = Wichtelrunde.find(params[:id])
    end

    def set_sender_wichtel
      @wichtel = @wichtelrunde.wichtels.where(lot_uuid: params[:uuid]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wichtelrunde_params
      params.fetch(:wichtelrunde, {})
    end

    def sender_wichtel_params
      params.require(:wichtel).permit(:shipped)
    end
end

app/controllers/wichtels_controller.rb
class WichtelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wichtelrunde, only: [:create, :update, :destroy]
  before_action :set_wichtel, only: [:update, :destroy]
  before_action :can_register, only: [:create, :update, :destroy]

  def create
    @wichtel = Wichtel.new wichtelrunde_params
    @wichtel.user = current_user
    @wichtel.wichtelrunde = @wichtelrunde
    @wichtel.save!

    flash[:notice] = t(".created")

    redirect_to @wichtelrunde
  end

  def update
    @wichtel.update wichtelrunde_params

    flash[:notice] = t(".updated")

    redirect_to @wichtelrunde
  end

  def destroy
    @wichtel.destroy

    flash[:notice] = t(".destroyed", register_until: l(@wichtelrunde.register_until))

    redirect_to @wichtelrunde
  end

  private
    def can_register
      if @wichtelrunde.registration_over
        flash[:alert] = t(".register_until_over")
        redirect_to @wichtelrunde
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_wichtelrunde
      @wichtelrunde = Wichtelrunde.find(params[:wichtelrunde_id])
    end

    def set_wichtel
      @wichtel = current_user.wichtels.where(id: params[:id], wichtelrunde: @wichtelrunde).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wichtelrunde_params
      params.require(:wichtel).permit(:shipping_address)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/wichtelrundes_helper.rb
module WichtelrundesHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, no_intra_emphasis: true)

    return markdown.render(text).html_safe
  end
end

app/helpers/wichtels_helper.rb
module WichtelsHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1">

    <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs float-xs-left">
          <li class="nav-item"><a class="nav-link active" data-toggle="tab" role="tab" href="#current-wichtelrunden"><%= t ".current_wichtelrunde" %></a></li>
          <li class="nav-item"><a class="nav-link" data-toggle="tab" role="tab" href="#past-wichtelrunden"><%= t ".past_wichtelrunden" %></a></li>
        </ul>
      </div>
      <div class="tab-content">
        <div class="tab-pane active" id="current-wichtelrunden" role="tabpanel">
          <% unless @current_wichtelrunden.empty? %>
            <div class="card-block">
              <p class="card-text"><%= t ".current_copy" %></p>
            </div>
            <ul class="list-group list-group-flush">
              <% @current_wichtelrunden.each do |wichtelrunde| %>
                <a href="<%= url_for wichtelrunde_path(wichtelrunde) %>" class="list-group-item list-group-item-action">
                  <h5 class="list-group-item-heading"><%= wichtelrunde.name %></h5>
                  <p class="list-group-item-text"><%= t ".wichtelrunde_excerpt", participants_count: wichtelrunde.wichtels.count, register_until: l(wichtelrunde.register_until) %></p>
                </a>
              <% end %>
            </ul>
          <% else %>
            <div class="card-block">
              <div class="alert alert-warning wichteln-card-alert" role="alert">Es gibt keine aktuellen Wichtelrunden!</div>
            </div>
          <% end %>
        </div>

        <div class="tab-pane" id="past-wichtelrunden" role="tabpanel">
          <% if @past_wichtelrunden.empty? %>
            <div class="card-block">
              <div class="alert alert-warning wichteln-card-alert" role="alert">Es gibt keine vergangenen Wichtelrunden!</div>
            </div>
          <% else %>
            <div class="card-block">
              <p class="card-text"><%= t ".past_copy" %></p>
            </div>
            <ul class="list-group list-group-flush">
              <% @past_wichtelrunden.each do |wichtelrunde| %>
                <%= link_to wichtelrunde_path(wichtelrunde), class: "list-group-item list-group-item-action" do %>
                  <h5 class="list-group-item-heading"><%= wichtelrunde.name %></h5>
                  <p class="list-group-item-text"><%= t ".wichtelrunde_excerpt", participants_count: wichtelrunde.wichtels.count, register_until: l(wichtelrunde.register_until) %></p>
                <% end %>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-header">
        <%= t ".instructions_headline" %>
      </div>
      <div class="card-block">
        <%= markdown t(".instructions") %>
      </div>
    </div>

    <div class="card">
      <div class="card-header">
        <%= t ".invite_headline" %>
      </div>
      <div class="card-block">
        <p><%= t ".invite_copy" %></p>

        <hr />

        <div class="container">
          <div class="col-sm-8 offset-sm-2">
            <div class="container">
              <%= form_tag invite_path do %>
                <div class="form-group row">
                  <%= label_tag :email, t('.invite_email'), class: "col-sm-4 col-form-label" %>
                  <div class="col-sm-8">
                    <%= email_field_tag :email, '', class: "form-control" %>
                  </div>
                </div>

                <div class="form-group row">
                  <div class="col-sm-8 offset-sm-4">
                    <%= submit_tag t('.invite_submit'), class: "btn btn-primary" %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wichteln</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <div class="container">
      <nav class="navbar navbar-dark bg-inverse wichteln-navbar">
        <button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"></button>
        <a class="navbar-brand" href="<%= url_for root_path %>">Wichteldings</a>
        <div class="collapse navbar-toggleable-md" id="navbarResponsive">
          <ul class="nav navbar-nav">
            <li class="nav-item">
              <%= link_to t(".nav_home"), root_path, class: "nav-link" %>
            </li>
          </ul>

          <% if user_signed_in? %>
            <ul class="nav navbar-nav float-sm-right">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="<%= url_for edit_user_registration_path %>" id="supportedContentDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.email %></a>
                <div class="dropdown-menu" aria-labelledby="supportedContentDropdown">
                  <a class="dropdown-item" href="<%= url_for edit_user_registration_path %>"><%= t ".nav_edit_account" %></a>
                  <%= link_to t(".nav_logout"), destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                </div>
              </li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav float-sm-right">
              <li class="nav-item"><%= link_to t(".nav_login"), new_user_session_path, class: "nav-link" %></li>
            </ul>
          <% end %>
        </div>
      </nav>

      <% if notice %>
        <div class="row">
          <div class="col-sm-10 offset-sm-1">
            <div class="alert alert-success" role="alert"><%= notice %></div>
          </div>
        </div>
      <% end %>

      <% if alert %>
        <div class="row">
          <div class="col-sm-10 offset-sm-1">
            <div class="alert alert-warning" role="alert"><%= alert %></div>
          </div>
        </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/wichtelrundes/sender_show.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1">
    <h2 class="wichteln-page-headline"><%= @wichtelrunde.name %></h2>

    <div class="card">
      <div class="card-header"><%= t ".partner_headline" %></div>
      <div class="card-block">
        <p><%= t ".partner_copy", ship_until: l(@wichtelrunde.ship_until) %></p>
        <dl class="row">
          <dt class="col-sm-2"><%= t ".receiver" %></dt>
          <dd class="col-sm-10"><pre><%= @wichtel.shipping_address %></pre></dd>
        </dl>

        <hr />

        <p><%= t ".confirm_copy" %></p>

        <div class="container">
          <%= form_tag sender_wichtelrunde_path(@wichtelrunde, @wichtel.lot_uuid), method: "PUT" do %>
            <div class="form-group row">
              <div class="col-sm-9 offset-sm-3">
                <%= hidden_field_tag "wichtel[shipped]", nil %>
                <%= check_box_tag "wichtel[shipped]", 1, @wichtel.shipped, id: :shipped %>
                <%= label_tag :shipped, t(".shipped_label") %>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-sm-9 offset-sm-3">
                <%= submit_tag t(".shipped_save"), class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/wichtelrundes/show.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1">
    <%= link_to t(".back"), :back, class: "wichteln-back-link" %>
    <br />

    <h2 class="wichteln-page-headline"><%= @wichtelrunde.name %></h2>

    <div class="card">
      <div class="card-header"><%= t ".rules_headline" %></div>
      <div class="card-block">
        <dl class="row">
          <dt class="col-sm-3"><%= t ".register_until" %></dt>
          <dd class="col-sm-9"><%= l @wichtelrunde.register_until %></dd>
          <dt class="col-sm-3"><%= t ".ship_until" %></dt>
          <dd class="col-sm-9"><%= l @wichtelrunde.ship_until %></dd>
          <dt class="col-sm-3"><%= t ".participants_count" %></dt>
          <dd class="col-sm-9"><%= t ".participants_counter", count: @wichtelrunde.wichtels.count %></dd>
          <dt class="col-sm-3"><%= t ".participation_status" %></dt>
          <dd class="col-sm-9">
            <% if @wichtel.new_record? %>
              <%= t ".not_participating" %>
            <% else %>
              <%= t ".is_participating" %>
              <% unless @wichtelrunde.registration_over %>
                <%= link_to t('.remove_participation'), [@wichtelrunde, @wichtel], data: { confirm: t(".are_you_sure") }, method: :delete, class: "btn btn-danger btn-sm" %>
              <% end %>
            <% end %>
          </dd>
          <% if @wichtelrunde.registration_over %>
            <dt class="col-sm-3"><%= t ".shipping_status" %></dt>
            <dd class="col-sm-9">
              <% if @wichtel.shipped %>
                <%= t ".is_shipped" %>
              <% else %>
                <%= t ".not_shipped" %>
              <% end %>
            </dd>
          <% end %>
        </dl>

        <% unless @wichtelrunde.rules.empty? %>
          <hr />
          <p><%= t ".rules_furthermore" %></p>
          <%= markdown @wichtelrunde.rules %>
        <% end %>
      </div>
    </div>

    <div class="card">
      <div class="card-header">
        <%= t ".participate_headline" %>
      </div>
      <div class="card-block">
        <% if @wichtelrunde.registration_over %>
          <div class="alert alert-warning" role="alert"><%= t ".registration_is_over" %></div>
        <% else %>
          <p><%= t ".registration_copy", register_until: l(@wichtelrunde.register_until) %></p>

          <hr />

          <div class="container">
            <div class="col-sm-8 offset-sm-2">
              <div class="container">
                <%= form_for [@wichtelrunde, @wichtel] do |f| %>
                  <div class="form-group row">
                    <%= f.label :shipping_address, t('.form_address'), class: "col-sm-3 col-form-label" %>
                    <div class="col-sm-9">
                      <%= f.text_area :shipping_address, class: "form-control", rows: 5, placeholder: t(".form_address_placeholder") %>
                    </div>
                  </div>

                  <div class="form-group row">
                    <div class="col-sm-9 offset-sm-3">
                      <%= submit_tag t('.form_participate'), class: "btn btn-primary" %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

  </div>
 </div>